- name: configure backend server
  hosts: backend
  become: yes
  vars:
  tasks:
  - name: disable nodejs
    ansible.builtin.coomand: dnf module disable nodejs -y

  - name: enable nodejs
    ansible.builtin.coomand: dnf module enable nodejs:20 -y

  - name: install nodejs
    ansible.builtin.dnf: 
    name: nodejs
    state: install

  - name: create expense user
    ansible.builtin.user: 
      name: expense